sonar.projectKey=cicd-tasklist-frontend-certifiant1
sonar.projectName=Tasklist Frontend
sonar.sources=src
sonar.exclusions=src/__tests__/**,src/main.tsx,src/index.css
sonar.coverage.exclusions=src/main.tsx,src/App.tsx,src/index.css
sonar.tests=src/__tests__
sonar.javascript.lcov.reportPaths=coverage/lcov.info
